# Generated by Django 4.1.5 on 2023-01-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('edad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'Persona',
                'db_table': 'persona',
                'ordering': ['-id'],
            },
        ),
    ]
